management:
  endpoints.web.exposure.include:
     "*"
  endpoint.health.show-details: always
  health.ratelimiters.enabled: true
  
resilience4j:
  ratelimiter:
    instances:
      climateRateLimiter:
        limit-for-period: 3
        limit-refresh-period: 120s
        timeout-duration: 10s
        register-health-indicator: true
        
spring:
  application:
    name: rate-limiter-design-pattern-using-spring
