spring:
  jackson.serialization.indent_output: true
management:
  endpoints.web.exposure.include:
    - "*"
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true
  health.ratelimiters.enabled: true
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
resilience4j.retry:
  instances:
    climateRetry:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.lang.RuntimeException
resilience4j.ratelimiter:
  instances:
    climateRateLimiter:
      limit-for-period: 5
      limit-refresh-period: 15s
      timeout-duration: 10s
      register-health-indicator: true